### PR TITLE
fix dev/preview errors

### PR DESCRIPTION
**Pull request by gioboa**
Fixup few things, now it works

please use `npm` or `pnpm` as package manager

### CODE REVIEW

**Comment by JiaojSun** [comment]
Roger that. Thank you very much.

May I ask whether this error has anything to do with the vite version? Because I saw that you changed the version number of vite.








在 2023-05-07 17:11:40，"Giorgio Boa" ***@***.***> 写道：

Fixup few things, now it works

please use npm or pnpm as package manager

You can view, comment on, or merge this pull request online at:

  https://github.com/JiaojSun/vite-host/pull/1

Commit Summary
7b48006 fix dev/preview errors
File Changes

(5 files)

Mpackage-lock.json (2991)
Mpackage.json (6)
Mtsconfig.json (3)
Mvite.config.ts (6)
Dyarn.lock (1287)
Patch Links:
https://github.com/JiaojSun/vite-host/pull/1.patch
https://github.com/JiaojSun/vite-host/pull/1.diff

**Comment by gioboa** [comment]
I changed that version because the new version of native federation package complained about that 😉

**Comment by JiaojSun** [comment]
So is the new version of native federation package incompatible with this version of vite? If my project must be vite packaged, do you suggest that I use webpack5 modulue federation or the plug-in provided by vite, Vite-plugin-Federation?

I know each has its own advantages, because you are more experienced, could you give me some advice? Thank you very much.












在 2023-05-08 14:35:13，"Giorgio Boa" ***@***.***> 写道：

I changed that version because the new version of native federation package complained about that

**Comment by gioboa** [comment]
In the PR all is working correctly so I can't understand your question

**Comment by JiaojSun** [comment]
Anyway, thank you. I just want you to talk a little bit more about technology











在 2023-05-09 17:41:02，"Giorgio Boa" ***@***.***> 写道：

In the PR all is working correctly so I can't understand your question

**Comment by gioboa** [comment]
Ok, drop me a message on twitter my handle is @giorgio_boa

**Pull request closed without merging**
